defmodule Nebulex.TinyLFU.AccessOrderDeque do
  @moduledoc """
  An access-ordered deque backed by two ETS tables for LRU ordering.

  Provides O(1) eviction of the least-recently-used entry and O(log n)
  insertion and touch (move-to-MRU) operations. Used by the W-TinyLFU
  policy to maintain LRU ordering within each cache segment (Window,
  Probation, Protected).

  ## Implementation Details

  Two ETS tables work together:

    * **Data table** (`:set`) — maps `key` → `order_key`, enabling O(1) lookup
      of a key's current position in the ordering.
    * **Order table** (`:ordered_set`) — maps `order_key` → `key`, maintaining
      entries sorted by access time. The LRU entry is always at the front
      (`:ets.first/1`).

  The `order_key` is generated by `:erlang.unique_integer([:monotonic])`,
  which guarantees both uniqueness and monotonic ordering.

  ## Concurrency

  This module is designed for **single-writer** usage. All mutation functions
  (`put/2`, `remove/2`, `evict_lru/1`) should be called from a single process
  (the maintenance queue processor). Read-only functions (`peek_lru/1`,
  `member?/2`, `size/1`) are safe to call from any process.

  The GenServer exists solely for ETS table lifecycle management (ownership).
  All API functions operate on ETS directly — no message passing.
  """

  use GenServer

  import Nebulex.Utils, only: [camelize_and_concat: 1]

  @enforce_keys [:data_table, :order_table]
  defstruct [:data_table, :order_table]

  @typedoc "AccessOrderDeque struct"
  @type t() :: %__MODULE__{
          data_table: :ets.table(),
          order_table: :ets.table()
        }

  ## Client API

  @doc """
  Starts an `AccessOrderDeque` process linked to the caller.

  ## Options

    * `:name` - (optional) atom used as the base name for the ETS tables
      and for registering the GenServer.

  ## Examples

      iex> {:ok, pid} = Nebulex.TinyLFU.AccessOrderDeque.start_link()
      iex> is_pid(pid)
      true

  """
  @spec start_link(keyword()) :: GenServer.on_start()
  def start_link(opts) do
    name = Keyword.fetch!(opts, :name)

    GenServer.start_link(__MODULE__, opts, name: name)
  end

  @doc """
  Returns the deque struct for the given registered name.

  The struct holds references to the ETS tables and is used by all
  other API functions.

  ## Examples

      iex> {:ok, _pid} = Nebulex.TinyLFU.AccessOrderDeque.start_link(name: :window)
      iex> deque = Nebulex.TinyLFU.AccessOrderDeque.get_deque(:window)
      iex> is_struct(deque, Nebulex.TinyLFU.AccessOrderDeque)
      true

  """
  @spec get_deque(GenServer.server()) :: t()
  def get_deque(server) do
    GenServer.call(server, :get_deque)
  end

  @doc """
  Inserts or touches a key in the deque (upsert semantics).

  If the key is **new**, it is added at the MRU (most recently used) position.
  If the key **already exists**, it is moved to the MRU position.

  Returns `:ok`.

  ## Examples

      iex> {:ok, _} = Nebulex.TinyLFU.AccessOrderDeque.start_link(name: :test_put)
      iex> deque = Nebulex.TinyLFU.AccessOrderDeque.get_deque(:test_put)
      iex> Nebulex.TinyLFU.AccessOrderDeque.put(deque, :a)
      :ok
      iex> Nebulex.TinyLFU.AccessOrderDeque.put(deque, :a)
      :ok

  """
  @spec put(t(), any()) :: :ok
  def put(%__MODULE__{data_table: data_table, order_table: order_table}, key) do
    case :ets.take(data_table, key) do
      [{^key, old_order_key}] ->
        # Key exists — take already removed from data table.
        # Delete old order entry and re-insert at MRU.
        true = :ets.delete(order_table, old_order_key)

        # Insert new order entry at MRU.
        new_order_key = new_order_key()
        true = :ets.insert(order_table, {new_order_key, key})
        true = :ets.insert(data_table, {key, new_order_key})

      [] ->
        # New key — add at MRU
        order_key = new_order_key()
        true = :ets.insert(order_table, {order_key, key})
        true = :ets.insert(data_table, {key, order_key})
    end

    :ok
  end

  @doc """
  Removes a key from the deque.

  Returns `{:ok, key}` if the key was found and removed, or `:error` if
  the key was not in the deque.

  ## Examples

      iex> {:ok, _} = Nebulex.TinyLFU.AccessOrderDeque.start_link(name: :test_remove)
      iex> deque = Nebulex.TinyLFU.AccessOrderDeque.get_deque(:test_remove)
      iex> Nebulex.TinyLFU.AccessOrderDeque.put(deque, :a)
      :ok
      iex> Nebulex.TinyLFU.AccessOrderDeque.remove(deque, :a)
      {:ok, :a}
      iex> Nebulex.TinyLFU.AccessOrderDeque.remove(deque, :a)
      :error

  """
  @spec remove(t(), any()) :: {:ok, any()} | :error
  def remove(%__MODULE__{data_table: data_table, order_table: order_table}, key) do
    case :ets.take(data_table, key) do
      [{^key, order_key}] ->
        # take already removed from data table, just clean up order table
        true = :ets.delete(order_table, order_key)

        {:ok, key}

      [] ->
        :error
    end
  end

  @doc """
  Removes and returns the least-recently-used (LRU) entry.

  Returns `{:ok, key}` or `:empty` if the deque is empty.

  ## Examples

      iex> {:ok, _} = Nebulex.TinyLFU.AccessOrderDeque.start_link(name: :test_evict)
      iex> deque = Nebulex.TinyLFU.AccessOrderDeque.get_deque(:test_evict)
      iex> Nebulex.TinyLFU.AccessOrderDeque.put(deque, :a)
      iex> Nebulex.TinyLFU.AccessOrderDeque.put(deque, :b)
      iex> Nebulex.TinyLFU.AccessOrderDeque.evict_lru(deque)
      {:ok, :a}

  """
  @spec evict_lru(t()) :: {:ok, any()} | :empty
  def evict_lru(%__MODULE__{order_table: order_table, data_table: data_table}) do
    case :ets.first_lookup(order_table) do
      :"$end_of_table" ->
        :empty

      {order_key, [{_order_key, key}]} ->
        true = :ets.delete(order_table, order_key)
        true = :ets.delete(data_table, key)

        {:ok, key}
    end
  end

  @doc """
  Returns the least-recently-used (LRU) key without removing it.

  Returns `{:ok, key}` or `:empty` if the deque is empty.

  ## Examples

      iex> {:ok, _} = Nebulex.TinyLFU.AccessOrderDeque.start_link(name: :test_peek)
      iex> deque = Nebulex.TinyLFU.AccessOrderDeque.get_deque(:test_peek)
      iex> Nebulex.TinyLFU.AccessOrderDeque.peek_lru(deque)
      :empty
      iex> Nebulex.TinyLFU.AccessOrderDeque.put(deque, :a)
      iex> Nebulex.TinyLFU.AccessOrderDeque.peek_lru(deque)
      {:ok, :a}

  """
  @spec peek_lru(t()) :: {:ok, any()} | :empty
  def peek_lru(%__MODULE__{order_table: order_table}) do
    case :ets.first_lookup(order_table) do
      :"$end_of_table" ->
        :empty

      {_order_key, [{_, key}]} ->
        {:ok, key}
    end
  end

  @doc """
  Removes all entries from the deque.

  Returns `:ok`. Intended for whole-cache invalidation
  (e.g., `delete_all/1`) where the entire deque must be wiped in one
  step, matching the synchronous `:ets.delete_all_objects/1` issued
  against the cache's data table on the hot path.

  ## Examples

      iex> {:ok, _} = Nebulex.TinyLFU.AccessOrderDeque.start_link(name: :test_clear)
      iex> deque = Nebulex.TinyLFU.AccessOrderDeque.get_deque(:test_clear)
      iex> Nebulex.TinyLFU.AccessOrderDeque.put(deque, :a)
      iex> Nebulex.TinyLFU.AccessOrderDeque.clear(deque)
      :ok
      iex> Nebulex.TinyLFU.AccessOrderDeque.size(deque)
      0

  """
  @spec clear(t()) :: :ok
  def clear(%__MODULE__{data_table: data_table, order_table: order_table}) do
    true = :ets.delete_all_objects(data_table)
    true = :ets.delete_all_objects(order_table)

    :ok
  end

  @doc """
  Returns whether the key is present in the deque.

  ## Examples

      iex> {:ok, _} = Nebulex.TinyLFU.AccessOrderDeque.start_link(name: :test_member)
      iex> deque = Nebulex.TinyLFU.AccessOrderDeque.get_deque(:test_member)
      iex> Nebulex.TinyLFU.AccessOrderDeque.member?(deque, :a)
      false
      iex> Nebulex.TinyLFU.AccessOrderDeque.put(deque, :a)
      iex> Nebulex.TinyLFU.AccessOrderDeque.member?(deque, :a)
      true

  """
  @spec member?(t(), any()) :: boolean()
  def member?(%__MODULE__{data_table: data_table}, key) do
    :ets.member(data_table, key)
  end

  @doc """
  Returns the number of entries in the deque.

  ## Examples

      iex> {:ok, _} = Nebulex.TinyLFU.AccessOrderDeque.start_link(name: :test_size)
      iex> deque = Nebulex.TinyLFU.AccessOrderDeque.get_deque(:test_size)
      iex> Nebulex.TinyLFU.AccessOrderDeque.size(deque)
      0

  """
  @spec size(t()) :: non_neg_integer()
  def size(%__MODULE__{order_table: order_table}) do
    :ets.info(order_table, :size)
  end

  ## GenServer callbacks

  @impl true
  def init(opts) do
    name = Keyword.fetch!(opts, :name)

    data_table =
      [name, Data]
      |> camelize_and_concat()
      |> :ets.new([
        :set,
        :public,
        decentralized_counters: true
      ])

    order_table =
      [name, Order]
      |> camelize_and_concat()
      |> :ets.new([
        :ordered_set,
        :public,
        decentralized_counters: true
      ])

    deque = %__MODULE__{
      data_table: data_table,
      order_table: order_table
    }

    {:ok, deque}
  end

  @impl true
  def handle_call(:get_deque, _from, deque) do
    {:reply, deque, deque}
  end

  ## Private functions

  @compile inline: [new_order_key: 0]
  defp new_order_key do
    :erlang.unique_integer([:monotonic])
  end
end
